/* Copyright (c) 1984 by Manx Software Systems */

extern char _sys_parm[18];	/* parameter area for ProDOS MLI calls */

#define	SYS_CREAT 	0xC0
#define	SYS_DSTRY 	0xC1
#define	SYS_RENAM 	0xC2
#define	SYS_SINFO 	0xC3
#define	SYS_GINFO 	0xC4
#define	SYS_ONLIN 	0xC5
#define	SYS_STPFX 	0xC6
#define	SYS_GTPFX 	0xC7
#define	SYS_OPEN  	0xC8
#define	SYS_NEWLN 	0xC9
#define	SYS_READ  	0xCA
#define	SYS_WRITE 	0xCB
#define	SYS_CLOSE 	0xCC
#define	SYS_FLUSH 	0xCD
#define	SYS_STMRK 	0xCE
#define	SYS_GTMRK 	0xCF
#define	SYS_STEOF 	0xD0
#define	SYS_GTEOF 	0xD1
#define	SYS_STBUF 	0xD2
#define	SYS_GTBUF 	0xD3
#define	SYS_ALINT 	0x40
#define	SYS_DALIN 	0x41
#define	SYS_RDBLK 	0x80
#define	SYS_WRBLK 	0x81
#define SYS_TIME	0x82

